### PR TITLE
Tt 3 js implementation

### PR DESCRIPTION
**Pull request by Andy258852**
Js implementation for the app.

### CODE REVIEW

**Comment by Nastik1811** [comment]
Overall looks good, except for this part
image

**Comment by Andy258852** [comment]
image
I've simplified the buttons logic this way! @Nastik1811 Could you took a glance and estimate please)

**Comment by Nastik1811** [comment]
You're using `a` for buttons and this is wrong

**Comment by Andy258852** [comment]
I've just fixed the issue. There are buttons instead of a now.

**Comment by Nastik1811** [comment]
Nice. What is your plan for the final milestone?

**Comment by Andy258852** [comment]
I am planning to implement some features related to keyboard trainer settings (For example a possibility to use custom text, choose if a user makes an error skip this symbol or not, etc). Also I think it would nice to do minor statistics to store in cache for example. To my mind It would be enough for the project to be completed. Are you agree. Could you tell me your thoughts please) @Nastik1811

**Review by Nastik1811 — APPROVED** [review]
Okay, go on then. Your work is quite neat, but according to the Approximate Grading I could give you only `6` for js. But if you have something to add at the last stage, the result mark might be higher

**Pull request merged**
